FROM nvidia/cuda:11.4.0-devel-ubuntu20.04
  
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    ffmpeg \
    libsm6 \
    libxext6 \
    git \
    ninja-build \
    libglib2.0-0 \
    libsm6 \
    libxrender-dev \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*
# RUN pip3 install --no-cache-dir torch==1.9.0 torchvision==0.10.0
RUN pip3 install --no-cache-dir torch==1.9.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
# RUN pip3 install --no-cache-dir torch torchvision

RUN pip3 install -U setuptools
RUN pip uninstall mmcv
# RUN pip3 install --no-cache-dir mmcv-full
RUN pip3 install --no-cache-dir mmcv-full==1.3.9 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html

RUN pip3 install --no-cache-dir mmdet==2.15.0

# auto-ml https://github.com/romanzes637/auto-ml
RUN git clone https://github.com/romanzes637/auto-ml.git /auto-ml
WORKDIR /auto-ml
