# For PYTORCH, CUDA and CUDNN see https://hub.docker.com/r/pytorch/pytorch/tags
# For MMCV, CUDA_MMCV see https://download.openmmlab.com/mmcv/dist/
# For MMDET see https://github.com/open-mmlab/mmdetection/blob/master/docs/get_started.md
# CUDA_MMCV should be equal to CUDA without "."
ARG PYTORCH="1.8.0"
ARG CUDA="11.1"
ARG CUDNN="8"
ARG CUDA_MMCV="111"
ARG MMCV="1.3.5"
ARG MMDET="2.13.0"

# PyTorch
FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel

# Redeclare ARG after FROM (see https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact)
ARG PYTORCH
ARG CUDA
ARG CUDNN
ARG CUDA_MMCV
ARG MMCV
ARG MMDET

# MMCV https://github.com/open-mmlab/mmcv
RUN pip install --no-cache-dir mmcv-full==${MMCV} -f https://download.openmmlab.com/mmcv/dist/cu${CUDA_MMCV}/torch${PYTORCH}/index.html

# MMDetection https://github.com/open-mmlab/mmdetection
RUN pip install mmdet==${MMDET}

# apt-get  https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsm6 \ 
    libxext6 \ 
    git \ 
    ninja-build \ 
    libglib2.0-0 \ 
    libsm6 \ 
    libxrender-dev \ 
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

# auto-ml https://github.com/romanzes637/auto-ml
RUN git clone https://github.com/romanzes637/auto-ml.git /auto-ml
WORKDIR /auto-ml
